database:
    driver: mysql
    host: 127.0.0.1
    port: 3306
    name: app
    user: root
    password:

project:
    name: 'Fundo Las Lomas'
    package: 'github.com/account/project' #required for go

output:
    dir: 'output/project'