parameters:

  packages:
    JSPSimple:
      model: JavaSimple
      controller: JSPSimple
      view: JSPSimple
    Struts2:
      model: Struts2Simple
      controller: Struts2Simple
      view: Struts2Simple
    Struts2Hibernate:
      model: Struts2HibernateSimple
      controller: Struts2HibernateSimple
      view: Struts2HibernateSimple