parameters:
  packages:
    JSPSimple:
      model: JavaSimple
      controller: JSPSimple
      view: JSPSimple
    Golang:
      assets: Golang
      model: Golang
      controller: Golang
#      view: Golang