parameters:

  packages:
    JSPSimple:
      model: JavaSimple
      controller: JSPSimple
      view: JSPSimple
    Struts2:
      model: Struts2Simple
      controller: Struts2Simple
      view: Struts2Simple