#!/usr/bin/env php
<?php
namespace CrudGenerator;

use App\DependencyInjection\Application;

// the autoloader
$loader = require __DIR__ . '/../vendor/autoload.php';

// create application
$application = new Application(__NAMESPACE__);

// and run
$application->run();
